version: '3.8'

services:
  # PostgreSQL Database for Product Service
  product-db:
    image: postgres:16-alpine  # Updated to PostgreSQL 16
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpass
    ports:
      - "5432:5432"
    volumes:
      - product-data:/var/lib/postgresql/data

  # PostgreSQL Database for Order Service
  order-db:
    image: postgres:16-alpine  # Updated to PostgreSQL 16
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data

  # Product Service (Java 24)
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productdb
      SPRING_DATASOURCE_USERNAME: productuser
      SPRING_DATASOURCE_PASSWORD: productpass
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - product-db

  # Order Service (Java 24)
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpass
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      PRODUCT_SERVICE_URL: http://product-service:8081
    depends_on:
      - order-db
      - product-service

volumes:
  product-data:
  order-data: